WebXemPhim/Areas/Admin/Controllers/TaiKhoanController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebXemPhim.Models;

namespace WebXemPhim.Areas.Admin.Controllers
{
    public class TaiKhoanController : BaseController
    {
        //
        // GET: /Admin/TaiKhoan/

        DataClasses1DataContext data = new DataClasses1DataContext();
        public ActionResult DSTaiKhoan()
        {
            var tk = data.TaiKhoans.ToList();
            return View(tk);
        }

        //Xóa TK
        public ActionResult XoaTK(string tendn)
        {
            TaiKhoan tk = data.TaiKhoans.SingleOrDefault(n => n.TenDN == tendn);
            if (tk == null)
            {
                Response.SubStatusCode = 404;
                return null;
            }
            data.TaiKhoans.DeleteOnSubmit(tk);
            data.SubmitChanges();
            return RedirectToAction("DSTaiKhoan");
        }
        //Thêm tài khoản
        [HttpGet]
        public ActionResult ThemTK()
        {
            return View();
        }

        [HttpPost]
        public ActionResult ThemTK(TaiKhoan tk ,FormCollection coll)
        {
            var tendn = coll["TenDN"];
            var mk = coll["MatKhau"];   
            //var taikhoan = from t in data.TaiKhoans where t.TenDN.Equals(tendn) select t.TenDN;
            var taikhoan = data.TaiKhoans.ToList();
            int kt=0;
            foreach (var item in taikhoan)
            {
                if (item.TenDN == tendn)
                    kt = 1;
            }
            if(String.IsNullOrEmpty(tendn))
                ViewData["Loi"]="Tên đăng nhập không được để chống";
            else if (String.IsNullOrEmpty(mk))
                ViewData["Loi1"] = "Mật khẩu không được để chống";
            else if (kt==1)
            {
                ViewData["Loi2"] = "Đã có tài khoản này";
            }
            else
            {
                tk.TenDN = tendn;
                tk.MatKhau = mk;
                data.TaiKhoans.InsertOnSubmit(tk);
                data.SubmitChanges();
                return RedirectToAction("DSTaiKhoan");
            }
            return View();
        }
        //Sửa
        public ActionResult SuaTK(string tendn)
        {
            var tk = data.TaiKhoans.First(n => n.TenDN == tendn);
            if (tk == null)
            {
                Response.SubStatusCode = 404;
                return null;
            }
            return View(tk);
        }

        [HttpPost]
        public ActionResult SuaTK(string tendn, FormCollection collection)
        {
            var tk = data.TaiKhoans.First(n => n.TenDN == tendn);
            var matkhau = collection["MatKhau"];
            var img = collection["Img"];
            if (String.IsNullOrEmpty(matkhau))
            {
                ViewData["Loi"] = "Không được để trống";
            }
            else
            {
                tk.MatKhau = matkhau;
                UpdateModel(tk);
                data.SubmitChanges();
                return RedirectToAction("DSTaiKhoan");
            }
            return this.SuaTK(tendn);
        }

    }
}

WebXemPhim/Areas/Admin/Views/TaiKhoan/DSTaiKhoan.cshtml
@using WebXemPhim.Models
@model List<TaiKhoan>
@{
    ViewBag.Title = "DSTaiKhoan";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutPage1.cshtml";
}

<div class="row">
    <div class="col-10"><h1 class="h3 mb-2 text-gray-800">Danh sách tài khoản</h1></div>
    <div class="col-2"><div style="float:right"><button type="button" class="btn btn-success">@Html.ActionLink("Thêm", "ThemTK")</button></div></div>
</div>
<br />
<!-- DataTales Example -->
<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">Danh sách</h6>
    </div>
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                <thead>
                    <tr>
                        <th>Tên đăng nhập</th>
                        <th>Mật khẩu</th>
                        <th>Quản Trị</th>
                        <th style="text-align: center">Chức năng</th>
                    </tr>
                </thead>
                <tfoot>
                    <tr>
                        <th>Tên đăng nhập</th>
                        <th>Mật khẩu</th>
                        <th>Quản Trị</th>
                        <th style="text-align: center">Chức năng</th>
                        </tr>
                </tfoot>
                <tbody>
                    @foreach (var item in Model)
                    {                     
                        <tr>
                            <td>@item.TenDN</td>
                            <td>@item.MatKhau</td>
                            <td>@item.Quyen</td>
                            <td style="width: 14%; text-align: center">
                                <a href="@Url.Action("SuaTK", new { tendn = item.TenDN })" class="btn btn-primary btn-icon-split">
                                    <span class="icon text-white-50">
                                        <i class="fas fa-edit"></i>
                                    </span>
                                </a>
                                <a onclick="return ConfirmXoa()" href="@Url.Action("XoaTK", new { tendn = item.TenDN })" class="btn btn-danger btn-icon-split">
                                     <span class="icon text-white-50">
                                        <i class="fas fa-trash"></i>
                                    </span>
                                </a>
                               
                                
                            </td>
                        </tr>              
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

<script>
    function ConfirmXoa() {
        if (confirm("Bạn có chắc muốn xóa tài khoản này không ?"))
            return true;
        else
            return false;
    }
        FocusEvent = false;
        checked = false;
</script>

WebXemPhim/Areas/Admin/Views/TaiKhoan/SuaTK.cshtml
@model WebXemPhim.Models.TaiKhoan
@{
    ViewBag.Title = "SuaTK";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutPage1.cshtml";
}

<h2>Sửa tài khoản</h2>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)

    <fieldset>
        <legend></legend>

        <div class="editor-field">
            <table>
                <tr>
                    <td>
                        <b>Tên đăng nhâp :  </b>
                    </td>
                    <td>
                        @Model.TenDN
                    </td>
                </tr>
                <tr>                 
                    <td style="width:125px"><b>Mật khẩu </b></td>
                    <td>@Html.TextBoxFor(model => model.MatKhau,new {@class="form-control"}) 
                        @ViewData["Loi"]</td>
                </tr>
            </table>
        </div>
        <p>
            <input type="submit" value="Lưu cập nhật" class="btn btn-success" />
        </p>
    </fieldset>
}
<div>
    @Html.ActionLink("Trở lại", "DSTaiKhoan","TaiKhoan")
</div>

WebXemPhim/Areas/Admin/Views/TaiKhoan/ThemTK.cshtml
@model WebXemPhim.Models.TaiKhoan

@{
    ViewBag.Title = "ThemTK";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutPage1.cshtml";
}


<h2>Thêm tài khoản</h2>

@using (Html.BeginForm("ThemTK","TaiKhoan",FormMethod.Post)) {
    @Html.ValidationSummary(true)

    <fieldset>
        <legend></legend>
        <div class="editor-label">
            <b>Tên đăng nhập</b>
        </div>
        <div class="editor-field">
            @Html.TextBoxFor(model => model.TenDN,new {@class="form-control"})
            @ViewData["Loi"]
            @Html.ValidationMessageFor(model => model.TenDN)
        </div>
        <div class="editor-label">
            <b>Mật khẩu</b>
        </div>
        <div class="editor-field">
            @Html.PasswordFor(model => model.MatKhau,new {@class="form-control"})
            @ViewData["Loi1"]
            @Html.ValidationMessageFor(model => model.MatKhau)
            @ViewData["Loi2"]
        </div>
        <p>            
            <input type="submit" value="Thêm" class="btn btn-success" />
            
        </p>
    </fieldset>
}
<div>
    @Html.ActionLink("Trở lại", "DSTaiKhoan","TaiKhoan")
</div>

WebXemPhim/Areas/Admin/Views/TaiKhoan/XoaTK.cshtml
@{
    ViewBag.Title = "XoaTK";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutPage1.cshtml";
}

<h2>XoaTK</h2>