WebXemPhim/Controllers/DangNhapDangKyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebXemPhim.Models;
using Facebook;
using System.Configuration;
namespace WebXemPhim.Controllers
{
    public class DangNhapDangKyController : Controller
    {
        //
        // GET: /DangNhapDangKy/
        DataClasses1DataContext data = new DataClasses1DataContext();

        private Uri RedirectUri
        {
            get
            {
                var uriBuilder = new UriBuilder(Request.Url);
                uriBuilder.Query = null;
                uriBuilder.Fragment = null;
                uriBuilder.Path = Url.Action("FacebookCallback");
                return uriBuilder.Uri;
            }
        }
        public ActionResult DangNhap()
        {
            var tl = data.TheLoais.ToList();
            var nam = data.Nams.ToList();
            var quocgia = data.QuocGias.ToList();
            ViewData["QuocGia"] = quocgia;
            ViewData["TheLoai"] = tl;
            ViewData["Nam"] = nam;
            return View();
        }
        [HttpPost]
        public ActionResult DangNhap(FormCollection collection)
        {
            var tl = data.TheLoais.ToList();
            var nam = data.Nams.ToList();
            ViewData["TheLoai"] = tl;
            ViewData["Nam"] = nam;
            var quocgia = data.QuocGias.ToList();
            ViewData["QuocGia"] = quocgia;

            var tendn = collection["TenDN"];
            var mk = collection["MatKhau"];
            if (String.IsNullOrEmpty(tendn))
                ViewData["Loi"] = "Bạn phải nhập tên đăng nhập";
            else if (String.IsNullOrEmpty(mk))
            {
                ViewData["Loi1"] = "Bạn phải nhập mật khẩu";
            }
            else
            {
                TaiKhoan tk = data.TaiKhoans.SingleOrDefault(n => n.TenDN.Equals(tendn) && n.MatKhau.Equals(mk));
                if (tk != null)
                {
                    if (tk.Quyen == true)//Admin
                    {
                        @Session["ten"] = tk.TenDN;
                        @Session["TK"] = tk.TenDN;
                        @Session["quyen"] = 1;
                        ViewBag.ThongBao = "Đăng nhập thành công admin";
                        return RedirectToAction("Home", "Admin/HomeAdmin/");
                    }
                    if (tk.Quyen == false || tk.Quyen == null)
                    {
                        @Session["quyen"] = null;
                        @Session["TK"] = tk.TenDN;
                        @Session["ten"] = tk.TenDN;
                        ViewBag.ThongBao = "Đăng nhập thành công";
                        return RedirectToAction("Index", "Home");
                    }
                }
                else
                {
                    ViewData["Loi2"] = "Tên đăng nhâp hoặc mật khẩu không đúng";
                }
            }

            return View();
        }
        [HttpGet]
        public ActionResult DangKy()
        {
            var tl = data.TheLoais.ToList();
            var nam = data.Nams.ToList();
            var quocgia = data.QuocGias.ToList();
            ViewData["QuocGia"] = quocgia;
            ViewData["TheLoai"] = tl;
            ViewData["Nam"] = nam;
            return View();
        }
        [HttpPost]
        public ActionResult DangKy(TaiKhoan tk, FormCollection coll)
        {
             var tl = data.TheLoais.ToList();
            var nam = data.Nams.ToList();
            var quocgia = data.QuocGias.ToList();
            ViewData["QuocGia"] = quocgia;
            ViewData["TheLoai"] = tl;
            ViewData["Nam"] = nam;
            var tendn = coll["TenDN"];
            var mk = coll["MatKhau"];
            var mknhaplai = coll["MatKhauNhapLai"];
            //var taikhoan = from t in data.TaiKhoans where t.TenDN.Equals(tendn) select t.TenDN;
            var taikhoan = data.TaiKhoans.ToList();
            int kt = 0;
            foreach (var item in taikhoan)
            {
                if (item.TenDN == tendn)
                    kt = 1;
            }
            if (String.IsNullOrEmpty(tendn))
                ViewData["Loi"] = "Tên đăng nhập không được để chống";
            else if (String.IsNullOrEmpty(mk))
                ViewData["Loi1"] = "Mật khẩu không được để chống";
            else if (kt == 1)
            {
                ViewData["Loi2"] = "Đã có tài khoản này";
            }
            else if(mk!=mknhaplai)
            {
                ViewData["Loi12"] = "mật khẩu nhập lại không đúng";
            }
            else
            {
                tk.TenDN = tendn;
                tk.MatKhau = mk;
                data.TaiKhoans.InsertOnSubmit(tk);
                data.SubmitChanges();
                return RedirectToAction("/DangNhap");
            }
            return View();
        }
        public ActionResult DangXuat()
        {
            @Session["ten"] = null;
            @Session["quyen"] = null;
            @Session["TK"] = null;
            return Redirect("/");

        }
        public ActionResult DangNhapFaceBook()
        {
            var fb = new FacebookClient();
            var loginUrl = fb.GetLoginUrl(new
            {
                client_id = ConfigurationManager.AppSettings["FbAppId"],
                client_secret = ConfigurationManager.AppSettings["FbAppSecret"],
                redirect_uri = RedirectUri.AbsoluteUri,
                response_type = "code",
                scope = "email",
            });

            return Redirect(loginUrl.AbsoluteUri);
        }
        public ActionResult FacebookCallback(string code, TaiKhoan tk, FormCollection coll)
        {
            var fb = new FacebookClient();
            dynamic result = fb.Post("oauth/access_token", new
            {
                client_id = ConfigurationManager.AppSettings["FbAppId"],
                client_secret = ConfigurationManager.AppSettings["FbAppSecret"],
                redirect_uri = RedirectUri.AbsoluteUri,
                code = code
            });


            var accessToken = result.access_token;
            if (!string.IsNullOrEmpty(accessToken))
            {
                fb.AccessToken = accessToken;

                dynamic me = fb.Get("me?fields=first_name,middle_name,last_name,id,email");
                string email = me.email;
                string userName = me.email;
                string firstname = me.first_name;
                string middlename = me.middle_name;
                string lastname = me.last_name;
                string aaaaaaaaa = firstname + "@321dSDFdgb";
                var taikhoan = data.TaiKhoans.ToList();
                int kt = 0;
                foreach (var item in taikhoan)
                {
                    if (item.TenDN == aaaaaaaaa)
                        kt = 1;
                }

                if (kt == 1)
                {
                    @Session["ten"] = firstname;
                    @Session["TK"] = aaaaaaaaa;
                    @Session["quyen"] = null;
                }
                else
                {
                    tk.TenDN = firstname + "@321dSDFdgb";
                    tk.MatKhau = "12312ABC@312jidqjv";
                    data.TaiKhoans.InsertOnSubmit(tk);
                    data.SubmitChanges();
                    @Session["TK"] = firstname;
                    @Session["quyen"] = null;

                }






            }
            return RedirectToAction("Index", "Home");
        }
    }
}

WebXemPhim/Views/DangNhapDangKy/DangKy.cshtml
@{
    ViewBag.Title = "DangKy";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@model WebXemPhim.Models.TaiKhoan
@using (Html.BeginForm("DangKy","DangNhapDangKy",FormMethod.Post)) {
    @Html.ValidationSummary(true)
<div class="container" style="padding-top:60px">
    <div class="row">
      <div class="col-sm-9 col-md-7 col-lg-5 mx-auto">
        <div class="card card-signin my-5">
          <div class="card-body">
            <h5 class="card-title text-center">Đăng ký</h5>
            <form class="form-signin">
              <div class="form-label-group">
                 @Html.TextBox("TenDN",null,new {@class="form-control"}) 
               @ViewData["Loi2"]
                  @ViewData["Loi"]
              </div>

              <div class="form-label-group">
                 @Html.Password("MatKhau",null,new {@class="form-control",})
                  @ViewData["Loi"]
                
              </div>
               <div class="form-label-group">
                @Html.Password("MatKhauNhapLai",null,new {@class="form-control",})
                @ViewData["Loi12"]
              </div>
               
              
              <button class="btn btn-lg btn-primary btn-block text-uppercase" type="submit">Đăng ký</button>
                <div style="padding-top:10px;margin-left:5px;">
                    <a style="color:#0094ff" href="~/DangNhapDangKy/DangNhap">Quay về đăng nhập</a>
                </div>
                
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
    }

WebXemPhim/Views/DangNhapDangKy/DangNhap.cshtml
@{
    ViewBag.Title = "DangNhap";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@ViewBag.ThongBao
@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)
    <fieldset>
        <legend></legend>
<div class="container" style="padding-top: 60px">
    <div class="row">
        <div class="col-sm-9 col-md-7 col-lg-5 mx-auto">
            <div class="card card-signin my-5">
                <div class="card-body">
                    <h5 class="card-title text-center">Đăng nhập</h5>
                    <form class="form-signin">
                        <div class="form-label-group">
                           @* <input type="email" id="inputEmail" class="form-control" placeholder="Email address" required autofocus>*@                            
                            @Html.TextBox("TenDN",null,new {@class="form-control"})                    
                            @ViewData["Loi"]
                            @ViewData["Loi12"]
                            
                        </div>
                        <div class="form-label-group">
                            @*<input type="password" id="inputPassword" class="form-control" placeholder="Password" required>*@
                            @Html.Password("MatKhau",null,new {@class="form-control",})
                            @ViewData["Loi1"]
                            @ViewData["Loi2"]
                        </div>
                        <div class="custom-control mb-3">
                            <input type="checkbox" id="customCheck1">
                            <label for="customCheck1">Nhớ mật khẩu</label>
                        </div>
                     
                        <button class="btn btn-lg btn-primary btn-block text-uppercase" type="submit" style="height:35px;font-size:12px">Đăng nhập</button>
                        
                        <hr class="my-4">

                       <a href="~/DangNhapDangKy/DangNhapFaceBook"> <button class="btn btn-lg btn-facebook btn-block text-uppercase" type="button" style="height:35px;font-size:12px" ><i class="fab fa-facebook-f mr-2"></i>Đăng nhập bằng Facebook</button></a>
                        <div style="padding-top: 10px; margin-left: 5px;">

                            <a style="color: #0094ff" href="~/DangNhapDangKy/DangKy">Đăng ký tài khoản</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
        </fieldset>
}