WebXemPhim/Areas/Admin/Controllers/DanhMucController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebXemPhim.Models;

namespace WebXemPhim.Areas.Admin.Controllers
{
    public class DanhMucController : BaseController
    {
        //
        // GET: /Admin/DanhMuc/
        DataClasses1DataContext data = new DataClasses1DataContext();


        WebXemPhim.Entity.dbDoAnWebEntities db = new Entity.dbDoAnWebEntities();
        public ActionResult TheLoai()
        {
            var tl = data.TheLoais.ToList();
            return View(tl);
        }
        [HttpGet]
        public ActionResult ThemTheLoai()
        {
            return View();
        }
        //Thêm thể loai
        [HttpPost]
        public ActionResult ThemTheLoai(TheLoai tl, FormCollection coll)
        {

            var ten = coll["TenTheLoai"];
            var theloai = data.TheLoais.ToList();

            if (String.IsNullOrEmpty(ten))
                ViewData["Loi1"] = "Tên thể loại không được để chống";

            else
            {
                foreach (var item in theloai)
                {
                    if (String.Compare(item.TenTheLoai, ten, true) == 0)
                    {
                        ViewData["Loi2"] = "Đã có thể loại này";
                        return View();
                    }
                }
                tl.TenTheLoai = ten;
                data.TheLoais.InsertOnSubmit(tl);
                data.SubmitChanges();
                return RedirectToAction("TheLoai");
            }
            return View();
        }
        //Xóa thể loai
        public ActionResult XoaTheLoai(int id)
        {
            TheLoai tl = data.TheLoais.SingleOrDefault(n => n.IDTheLoai == id);
            if (tl == null)
            {
                Response.SubStatusCode = 404;
                return null;
            }
            data.TheLoais.DeleteOnSubmit(tl);
            data.SubmitChanges();
            return RedirectToAction("TheLoai");
        }
        //Sửa thể loại
        public ActionResult SuaTheLoai(int id)
        {
            var tl = data.TheLoais.First(n => n.IDTheLoai == id);
            if (tl == null)
            {
                Response.SubStatusCode = 404;
                return null;
            }
            return View(tl);
        }

        [HttpPost]
        public ActionResult SuaTheLoai(int id, FormCollection collection)
        {
            var tl = data.TheLoais.First(n => n.IDTheLoai == id);
            var ten = collection["TenTheLoai"];
            var theloai = data.TheLoais.ToList();
            foreach (var item in theloai)
            {
                if (String.Compare(item.TenTheLoai, ten, true) == 0 && item.IDTheLoai != id)
                {
                    ViewData["Loi2"] = "Tên thể loại đã tồn tại";
                    return this.SuaTheLoai(id);
                }
            }
            if (String.IsNullOrEmpty(ten))
            {
                ViewData["Loi1"] = "Tên thể loại không được để trống";
            }
            else
            {
                tl.TenTheLoai = ten;
                UpdateModel(tl);
                data.SubmitChanges();
                return RedirectToAction("TheLoai");
            }
            return this.SuaTheLoai(id);
        }
        //-----------------------------------------Năm Phát Hành-------------------------------------------
        public ActionResult NamPhatHanh()
        {
            var nam = data.Nams.ToList();
            return View(nam);
        }

        [HttpGet]
        public ActionResult ThemNam()
        {
            return View();
        }
        //Thêm thể loai
        [HttpPost]
        public ActionResult ThemNam(Nam tl, FormCollection coll)
        {
            var ten = (coll["TenNam"]);
            var namph = data.Nams.ToList();

            if (string.IsNullOrEmpty(ten))
            {
                ViewData["Loi1"] = "Năm phát hành không được để chống";
            }
            else
            {
                foreach (var item in namph)
                {
                    if (item.TenNam == int.Parse(ten))
                    {
                        ViewData["Loi2"] = "Đã có năm phát hành này";
                        return View();
                    }
                }
                tl.TenNam = int.Parse(ten);
                data.Nams.InsertOnSubmit(tl);
                data.SubmitChanges();
                return RedirectToAction("NamPhatHanh");
            }
            return View();
        }
        //Xóa thể loai
        public ActionResult XoaNam(int id)
        {
            Nam tl = data.Nams.SingleOrDefault(n => n.MaNam == id);
            if (tl == null)
            {
                Response.SubStatusCode = 404;
                return null;
            }
            data.Nams.DeleteOnSubmit(tl);
            data.SubmitChanges();
            return RedirectToAction("NamPhatHanh");
        }
        //Sửa thể loại
        public ActionResult SuaNam(int id)
        {
            var tl = data.Nams.First(n => n.MaNam == id);
            if (tl == null)
            {
                Response.SubStatusCode = 404;
                return null;
            }
            return View(tl);
        }

        [HttpPost]
        public ActionResult SuaNam(int id, FormCollection collection)
        {
            var tl = data.Nams.First(n => n.MaNam == id);
            var namph = data.Nams.ToList();
            var ten = collection["TenNam"];
            if (string.IsNullOrEmpty(ten.ToString()))
            {
                ViewData["Loi1"] = "Năm phát hành không được để trống";
            }
            else
            {
                foreach (var item in namph)
                {
                    if (item.TenNam == int.Parse(ten) && item.MaNam != id)
                    {
                        ViewData["Loi2"] = "Đã có năm phát hành này";
                        return this.SuaNam(id);
                    }
                }
                tl.TenNam = int.Parse(ten);
                UpdateModel(tl);
                data.SubmitChanges();
                return RedirectToAction("NamPhatHanh");
            }
            return this.SuaNam(id);
        }
        //-----------------------------------------Quốc Gia--------------------------------------------
        public ActionResult QuocGia()
        {
            var qg = data.QuocGias.ToList();
            return View(qg);
        }
        [HttpGet]
        public ActionResult ThemQuocGia()
        {
            return View();
        }
        //Thêm thể loai
        [HttpPost]
        public ActionResult ThemQuocGia(QuocGia qg, FormCollection coll)
        {
            var ten = coll["TenQG"];
            var quocgia = data.QuocGias.ToList();

            if (String.IsNullOrEmpty(ten))
                ViewData["Loi1"] = "Tên quốc gia không được để chống";

            else
            {
                foreach (var item in quocgia)
                {
                    if (String.Compare(item.TenQG, ten, true) == 0)
                    {
                        ViewData["Loi2"] = "Đã có quốc gia này rồi !!!";
                        return View();
                    }
                }
                qg.TenQG = ten;
                data.QuocGias.InsertOnSubmit(qg);
                data.SubmitChanges();
                return RedirectToAction("QuocGia");
            }
            return View();
        }
        //Xóa thể loai
        public ActionResult XoaQuocGia(int id)
        {
            QuocGia qg = data.QuocGias.SingleOrDefault(n => n.MaQG == id);
            if (qg == null)
            {
                Response.SubStatusCode = 404;
                return null;
            }
            data.QuocGias.DeleteOnSubmit(qg);
            data.SubmitChanges();
            return RedirectToAction("QuocGia");
        }
        //Sửa thể loại
        public ActionResult SuaQuocGia(int id)
        {
            var qg = data.QuocGias.First(n => n.MaQG == id);
            if (qg == null)
            {
                Response.SubStatusCode = 404;
                return null;
            }
            return View(qg);
        }

        [HttpPost]
        public ActionResult SuaQuocGia(int id, FormCollection collection)
        {
            var qg = data.QuocGias.First(n => n.MaQG == id);
            var ten = collection["TenQG"];
            var quocgia = data.QuocGias.ToList();
            foreach (var item in quocgia)
            {
                if (String.Compare(item.TenQG, ten, true) == 0 && item.MaQG != id)
                {
                    ViewData["Loi2"] = "Quốc gia này đã tồn tại";
                    return this.SuaQuocGia(id);
                }
            }
            if (String.IsNullOrEmpty(ten))
            {
                ViewData["Loi1"] = "Tên quốc gia không được để trống";
            }
            else
            {
                qg.TenQG = ten;
                UpdateModel(qg);
                data.SubmitChanges();
                return RedirectToAction("QuocGia");
            }
            return this.SuaQuocGia(id);
        }


        //-------------------------------------------BANNER------------------------------------------------------
        public ActionResult Banner()
        {
            var ALL_Phim = from tt in data.Banners select tt;
            return View(ALL_Phim);
        }
        //Sửa Hình banner
        public ActionResult SuaBanner(int id)
        {
            Banner banner = data.Banners.SingleOrDefault(n => n.ID == id);
            if (banner == null)
            {
                Response.SubStatusCode = 404;
                return null;
            }
            ViewData["IDPhim"] = new SelectList(data.DSPhimBos, "ID", "TenPhim", banner.IDPhim);
            return View(banner);
        }

        [HttpPost]
        [ValidateInput(false)]

WebXemPhim/Areas/Admin/Views/DSPhim/CTTapPhimBo.cshtml
@using WebXemPhim.Models
@{
    ViewBag.Title = "CTTapPhimBo";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutPage1.cshtml";
}
<div class="row">
    <div class="col-10"><h1 class="h3 mb-2 text-gray-800">Danh sách các tập phim</h1></div>                                             
    <div class="col-2">
        <div style="float:right">
        <button type="button" class="btn btn-success">@Html.ActionLink("Thêm", "ThemTapPhim", new { id = ViewData["Id"] })

        </button>

        </div>
    </div>
</div>
<br />
<br />
<!-- DataTales Example -->
<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">Danh sách</h6>
    </div>
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                <thead>
                    <tr>
                        <th style="width: 30%">Tên Phim</th>
                        <th style="width: 30%">Tập phim</th>
                        <th style="width: 30%">Link</th>
                        <th>Chức năng</th>
                    </tr>
                </thead>
                <tfoot>
                    <tr>
                        <th>Tên Phim</th>
                        <th>Tập phim</th>
                        <th>Link</th>
                        <th>Chức năng</th>
                    </tr>
                </tfoot>
                <tbody>
                    @foreach (var item in Model)
                    {                     
                        <tr>
                            <td>@item.DSPhimBo.TenPhim</td>
                            <td>@item.TapPhim</td>
                            <td>
                                <p style="overflow: hidden; -webkit-line-clamp: 1; display: -webkit-box; -webkit-box-orient: vertical;">
                                    @item.Link<p />
                            </td>
                            <td>
                                
                                <a href="@Url.Action("SuaTap", new { id = item.ID, tapphim = item.TapPhim})" class="btn btn-primary btn-icon-split">
                                    <span class="icon text-white-50">
                                        <i class="fas fa-edit"></i>
                                    </span>
                                </a>
                                <a onclick="return ConfirmXoa()" href="@Url.Action("XoaTapPhim", new { id = item.IDPhim })" class="btn btn-danger btn-icon-split">
                                     <span class="icon text-white-50">
                                        <i class="fas fa-trash"></i>
                                    </span>
                                </a></td>
                        </tr>     
                                
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>
<a href="@Url.Action("ThemTapPhim", new { id = ViewData["Id"]})" class="btn btn-primary btn-icon-split">  
    Thêm 
</a>
<script>
    function ConfirmXoa() {
        if (confirm("Bạn có chắc muốn xóa tài khoản này không ?"))
            return true;
        else
            return false;
    }
    FocusEvent = false;
    checked = false;
</script>

WebXemPhim/Areas/Admin/Views/DSPhim/ChiTietPhimLe.cshtml
@{
    ViewBag.Title = "ChiTietPhimLe";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutPage1.cshtml";
}

<fieldset>
    <legend></legend>
    <div class="row">
    <div class="col-10"><h1 class="h3 mb-2 text-gray-800">Thông tin phim :@Model.TenPhim</div>                                             
    <div class="col-2">
        <div style="float:right">
        <button type="button" class="btn btn-success">@Html.ActionLink("Sửa Phim", "SuaPhimLe", new { id =@Model.ID})

        </button>

        </div>
    </div>
</div>
<br />
<br />
    <div class="row" style="border-radius: 10px">
        <div class="col-xl-3 col-md-4 col-sm-4" style="padding: 5px;">
            <img style="height:340px;width:100%;" src="~/Content/Images/@Model.Img" />
        </div>
        <div class="col-xl-8 col-md-7 col-sm-7" style="padding-top: 10px">
            <div>
                <b>Tên Phim </b>
                @Model.TenPhim
                @ViewData["Loi"]
            </div>
            <div>
                <b>Nội dung</b>
                @Model.NoiDung
            </div>
            <div>
                <b>Năm phát hành</b>

                @ViewData["nam"]
           
            </div>
            <div>
                <b>Thể loại</b>
                @ViewData["tl"]

            </div>
            <div>
                <b>Quốc gia</b>

                @ViewData["quocgia"]
                   
            </div>

            <div>
                <b>Thời lượng</b>
                @Model.ThoiLuong
            </div>
            <div>
                <b>Lượt Xem</b>
                @Model.LuotXem
            </div>
        </div>
    </div>
</fieldset>
<div>
    <button type="button" class="btn btn-success">@Html.ActionLink("Trở Lại", "DSPhimLe")
    </button>
</div>

WebXemPhim/Areas/Admin/Views/DSPhim/DSPhimBo.cshtml
@{
    ViewBag.Title = "DSPhimBo";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutPage1.cshtml";
}
<div class="row">
    <div class="col-10">
        <h1 class="h3 mb-2 text-gray-800">Danh sách phim bộ</h1>
    </div>
    <div class="col-2">
        <div style="float: right">
            <button type="button" class="btn btn-success">@Html.ActionLink("Thêm", "ThemPhimBo")</button></div>
    </div>
</div>
<br />

   <div class="row">
@foreach (var item in Model)
{
    <div class="col-lg-3 col-md-4 col-sm-6 col-12">
        <div class="card mb-5 box-shadow">
            <div style="height:330px">                          
                        <a href="@Url.Action("CTTapPhimBo", new { id = item.ID })"><img class="card-img-top" src="~/Content/Images/@item.Img" alt="Card image cap"></a>
                </div>                        
            <div class="card-body" style="margin-left:-15px">
                <p class="card-text" style="text-align:left;overflow: hidden;-webkit-line-clamp:1;display: -webkit-box;-webkit-box-orient: vertical;"><b>Tên phim : </b>@item.TenPhim</p>
               <p class="card-text" style="overflow: hidden;-webkit-line-clamp:3;display: -webkit-box;-webkit-box-orient: vertical;"><b>Nội dung : </b>@item.NoiDung</p>                
                <p class="card-text"><b>Thể Loại : </b>@item.TheLoai.TenTheLoai</p>
                <p class="text-muted"><b>Số Tập :</b>@item.ThoiLuong</p>
                <p class="card-text"><b>Năm Phát Hành : </b>@item.Nam.TenNam</p>
                <div class="d-flex justify-content-between align-items-center">
                    <div>                    
                        @*<a onclick="return ConfirmXoa()" href="@Url.Action("XoaPhim", new { id = item.ID })">Xóa</a>*@
                        @Html.ActionLink("Thêm tập", "ThemTapPhim", new { id = item.ID })
                    </div>
                    <div>
                        @Html.ActionLink("Sửa", "SuaPhim", new { id = item.ID })
                    </div>             
                </div>
            </div>
        </div>
    </div>                               
}
</div> 

<script>
    function ConfirmXoa() {
        if (confirm("Bạn có chắc muốn xóa phim này không?"))
            return true;
        else
            return false;
    }
        FocusEvent = false;
        checked = false;
</script>

WebXemPhim/Areas/Admin/Views/DSPhim/DSPhimLe.cshtml
@{
    ViewBag.Title = "DSPhimLe";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutPage1.cshtml";
}

<div class="row">
    <div class="col-10">
        <h1 class="h3 mb-2 text-gray-800">Danh sách phim lẻ</h1>
    </div>
    <div class="col-2">
        <div style="float: right">
            <button type="button" class="btn btn-success">@Html.ActionLink("Thêm", "ThemPhimLe")</button></div>
    </div>
</div>
<br />
<div class="row">
    @foreach (var item in Model)
    {
        <div class="col-lg-3 col-md-4 col-sm-6 col-12">
            <div class="card mb-5 box-shadow">
                <div style="height: 330px">
                    <a href="@Url.Action("ChiTietPhimLe", new { id = item.ID})">
                        <img class="card-img-top" src="~/Content/Images/@item.Img" alt="Card image cap"></a>
                </div>
                <div class="card-body" style="margin-left: -15px">
                    <p class="card-text" style="text-align: left; overflow: hidden; -webkit-line-clamp: 1; display: -webkit-box; -webkit-box-orient: vertical;"><b>Tên phim : </b>@item.TenPhim</p>
                    <p class="card-text" style="overflow: hidden; -webkit-line-clamp: 3; display: -webkit-box; -webkit-box-orient: vertical;"><b>Nội dung : </b>@item.NoiDung</p>
                    <p class="card-text"><b>Năm Phát Hành : </b>@item.Nam.TenNam</p>
                    <p class="card-text"><b>Thể Loại : </b>@item.TheLoai.TenTheLoai</p>
                    <div class="d-flex justify-content-between align-items-center">
                        <div class="btn-group">                           
                            <button type="button" class="btn btn-sm ">@Html.ActionLink("Sửa", "SuaPhimLe", new { id = item.ID })</button>
                        </div>
                        <small class="text-muted">@item.ThoiLuong</small>
                    </div>
                </div>
            </div>
        </div>                               
    }
</div>

WebXemPhim/Areas/Admin/Views/DSPhim/SuaPhim.cshtml
@model WebXemPhim.Models.DSPhimBo
@{
    ViewBag.Title = "SuaPhim";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutPage1.cshtml";
}

<script src="https://cdn.tiny.cloud/1/no-api-key/tinymce/5/tinymce.min.js" referrerpolicy="origin"></script>
<script>tinymce.init({ selector: 'textarea' });</script>
<div class="row">
    <div class="col-10">
        <h1 class="h3 mb-2 text-gray-800">Sửa Phim</h1>
    </div>
</div>

@using (Html.BeginForm("SuaPhim", "DSPhim", FormMethod.Post, new {@enctype="multipart/form-data" }))
{
    @Html.AntiForgeryToken()    
    @Html.ValidationSummary(true)

    <fieldset>
        <legend></legend>
        <div class="row" style=" border-radius: 10px">

            <div class="col-xl-3 col-md-4 col-sm-4" style="padding: 5px;">
                <img style="height:340px;width:100%;" src="~/Content/Images/@Model.Img" />
                <input style="padding-top: 5px" type="file" name="fileUpload">  
                @ViewBag.ThongBao         
            </div>
            <div class="col-xl-8 col-md-7 col-sm-7" style="padding-top: 10px">
                <div>
                    <b>Tên Phim </b>
                    @Html.TextBoxFor(model => model.TenPhim, new { @class = "form-control" })
                    @ViewData["Loi"]
                </div>
                <div>
                    <b>Nội dung</b>
                   @*<textarea name="NoiDung">@Model.NoiDung</textarea>*@
                     @Html.TextBoxFor(model => model.NoiDung, new { @class = "form-control" })                    
                </div>
                <div>
                    <b>Năm phát hành</b>
                    @Html.DropDownList("NamPH", null, new { @class = "form-control" })
                </div>
                <div>
                    <b>Thể loại</b>
                    @Html.DropDownList("IDTheLoai" ,null, new { @class = "form-control" })
                </div>
                <div>
                    <b>Quốc gia</b>
                    @Html.DropDownList("IDQuocGia", null, new { @class = "form-control" })
                </div>
                
                <div>
                    <b>Thời lượng</b>
                    @Html.TextBoxFor(model => model.ThoiLuong, null, new { @class = "form-control" })
                    @ViewData["Loi1"]
                </div>
            </div>
        </div>
        <div> 
            <p>
              <input type="submit" value="Lưu cập nhật" class="btn btn-success" />
                </p></div>
        
    </fieldset>
}
<div>
    @Html.ActionLink("Trở lại", "DSPhimBo", "DSPhim")
</div>

WebXemPhim/Areas/Admin/Views/DSPhim/SuaPhimLe.cshtml
@model WebXemPhim.Models.DSPhimLe
@{
    ViewBag.Title = "SuaPhimLe";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutPage1.cshtml";
}
<div class="row">
    <div class="col-10">
        <h1 class="h3 mb-2 text-gray-800">Sửa Phim</h1>
    </div>
</div>

@using (Html.BeginForm("SuaPhimLe", "DSPhim", FormMethod.Post, new { @enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()    
    @Html.ValidationSummary(true)

    <fieldset>
        <legend></legend>
        <div class="row" style="border-radius: 10px">

            <div class="col-xl-3 col-md-4 col-sm-4" style="padding: 5px;">
                <img style="height:340px;width:100%;" src="~/Content/Images/@Model.Img" />
                <input style="padding-top: 5px" type="file" name="fileUpload">
                @ViewBag.ThongBao
            </div>
            <div class="col-xl-8 col-md-7 col-sm-7" style="padding-top: 10px">
                <div>
                    <b>Tên Phim </b>
                    @Html.TextBoxFor(model => model.TenPhim, new { @class = "form-control" })
                    @ViewData["Loi"]
                </div>
                <div>
                    <b>Nội dung</b>
                    @*<textarea name="NoiDung">@Model.NoiDung</textarea>*@
                    @Html.TextBoxFor(model => model.NoiDung, new { @class = "form-control" })
                </div>
                <div>
                    <b>Năm phát hành</b>
                    @Html.DropDownList("NamPH", null, new { @class = "form-control" })
                </div>
                <div>
                    <b>Thể loại</b>
                    @Html.DropDownList("IDTheLoai", null, new { @class = "form-control" })
                </div>
                <div>
                    <b>Quốc gia</b>
                    @Html.DropDownList("IDQuocGia", null, new { @class = "form-control" })
                </div>

                <div>
                    <b>Thời lượng</b>
                    @Html.TextBoxFor(model => model.ThoiLuong, null, new { @class = "form-control" })
                    @ViewData["Loi1"]
                </div>
            </div>
        </div>
        <div>
            <p>
                <input type="submit" value="Lưu cập nhật" class="btn btn-success" />
            </p>
        </div>

    </fieldset>
}
<div>
    <button type="button" class="btn btn-success">@Html.ActionLink("Trở Lại", "ChiTietPhimLe", new { id = @Model.ID })
    </button>
</div>

WebXemPhim/Areas/Admin/Views/DSPhim/SuaTap.cshtml
@{
    ViewBag.Title = "SuaTap";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutPage1.cshtml";
}
@model WebXemPhim.Models.CTTapPhim
@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)

    <fieldset>
        <legend></legend>

        <div class="editor-field">
            <table>
                <tr>
                    <td>
                        <b>ID phim  </b>
                    </td>
                    <td>
                        @Model.ID
                    </td>
                </tr>
                <tr>                 
                    <td style="width:125px"><b> Tập phim</b></td>
                    
                      <td>@Model.TapPhim
                    </td>
                </tr>
                <tr>                 
                    <td style="width:125px"><b> Link phim</b></td>
                    <td>@Html.TextBoxFor(model => model.Link,new {@class="form-control"}) 
                        </td>
                        <td style="color:red">
                        @ViewData["Loi1"]
                             @ViewData["Loi2"]
                        </td>
                </tr>
            </table>
        </div>
        <p>
            <input type="submit" value="Lưu cập nhật" class="btn btn-success" />
        </p>
    </fieldset>
}
<div>
    @Html.ActionLink("Trở lại", "QuocGia","DanhMuc")
</div>

WebXemPhim/Areas/Admin/Views/DSPhim/ThemPhimBo.cshtml
@model WebXemPhim.Models.DSPhimBo
@{
    ViewBag.Title = "ThemPhimBo";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutPage1.cshtml";
}
@using (Html.BeginForm("ThemPhimBo", "DSPhim", FormMethod.Post, new {@enctype="multipart/form-data" }))
{
    @Html.AntiForgeryToken()   
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Thêm Phim Bộ</legend>

       <p>Tên Phim</p>
            @Html.TextBox("TenPhim", null, new { @class = "form-control" })
        <p >
            Nội dung       
            @Html.TextBox("NoiDung", null, new { @class = "form-control" })
        </p>

        <p>
            Năm Phát Hành
              @Html.DropDownList("NamPH", null, new { @class = "form-control" })
        </p>
        <p >
            Thể Loại
             @Html.DropDownList("IDTheLoai", null, new { @class = "form-control" })
        </p>
        <p >
            Thời Lượng
            @Html.TextBox("ThoiLuong", null, new { @class = "form-control" })
        </p>
        <p>
            Hình
           <input type="file" name="fileupload" />           
        </p>        
        <p>
            Quốc Gia
            @Html.DropDownList("IDQuocGia", null, new { @class = "form-control" })
        </p>
        <p>
            <input type="submit" value="Thêm" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Trờ về", "DSPhimBo")
</div>

WebXemPhim/Areas/Admin/Views/DSPhim/ThemPhimLe.cshtml
@model WebXemPhim.Models.DSPhimLe
@{
    ViewBag.Title = "ThemPhimLe";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutPage1.cshtml";
}
@using (Html.BeginForm("ThemPhimLe", "DSPhim", FormMethod.Post, new {@enctype="multipart/form-data" }))
{
    @Html.AntiForgeryToken()   
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Thêm Phim Lẻ</legend>

       <p>Tên Phim</p>
            @Html.TextBox("TenPhim", null, new { @class = "form-control" })
        <p >
            Nội dung       
            @Html.TextBox("NoiDung", null, new { @class = "form-control" })
        </p>

        <p>
            Năm Phát Hành
              @Html.DropDownList("NamPH", null, new { @class = "form-control" })
        </p>
        <p >
            Thể Loại
             @Html.DropDownList("IDTheLoai", null, new { @class = "form-control" })
        </p>
        <p >
            Thời Lượng
            @Html.TextBox("ThoiLuong", null, new { @class = "form-control" })
        </p>
        <p>
            Hình
           <input type="file" name="fileupload" />           
        </p>        
        <p>
            Quốc Gia
            @Html.DropDownList("IDQuocGia", null, new { @class = "form-control" })
        </p>
        <p>
            Link
            @Html.TextBoxFor(model => model.Link,new {@class="form-control"})
        </p>
        <p>
            <input type="submit" value="Thêm" />
        </p>
    </fieldset>
}
<div>
    @Html.ActionLink("Trờ về", "DSPhimLe")
</div>

WebXemPhim/Areas/Admin/Views/DSPhim/ThemTapPhim.cshtml
@model WebXemPhim.Models.CTTapPhim
@{
    ViewBag.Title = "ThemTapPhim";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutPage1.cshtml";
}


@using (Html.BeginForm("ThemTapPhim","DSPhim")) {
    @Html.ValidationSummary(true)

    <fieldset>
        <legend></legend>
        <div class="editor-label">
            <p>Tên Phim : <b>@ViewData["TenPhim"]</b> </p>
        </div>
        <div class="editor-field">
           
        </div>
        <div class="editor-label">
            <p>Thêm tập : <b>@ViewData["TapPhim"]</b></p> 
        </div>
        <div class="editor-label">
            <b>Link Phim</b>
        </div>
        <div class="editor-field">
            @Html.TextBoxFor(model => model.Link,new {@class="form-control"})
            @ViewData["Loi1"]
            @Html.ValidationMessageFor(model => model.Link)
            @ViewData["Loi2"]
        </div>
        <p>            
            <input type="submit" value="Thêm" class="btn btn-success" />            
        </p>
    </fieldset>
}
<div>
    @Html.ActionLink("Trở lại", "CTTapPhimBo")
</div>